
//constant  fro diagnosis

export const  FETCHING_PEOPLE = 'FETCHING_PEOPLE';
export const  FETCHING_PEOPLE_SUCCESS = 'FETCHING_PEOPLE_SUCCESS';
export const  FETCHING_PEOPLE_SUCCESS_MORE = 'FETCHING_PEOPLE_SUCCESS_MORE';
export const  FETCHING_PEOPLE_FAILURE = 'FETCHING_PEOPLE_FAILURE';

//addiontional for diagnosis Long term
export const  FETCHING_LONGTERM_PEOPLE = 'FETCHING_LONGTERM_PEOPLE';
export const  FETCHING_LONGTERM_PEOPLE_SUCCESS = 'FETCHING_LONGTERM_PEOPLE_SUCCESS';
export const  FETCHING_LONGTERM_PEOPLE_SUCCESS_MORE = 'FETCHING_LONGTERM_PEOPLE_SUCCESS_MORE';
export const  FETCHING_LONGTERM_PEOPLE_FAILURE = 'FETCHING_LONGTERM_PEOPLE_FAILURE';


//constant for allergies
export const GETTING_ALLERGIES = 'GETTING_ALLERGIES';
export const GETTING_ALLERGIES_SUCCESS = 'GETTING_ALLERGIES_SUCCESS';
export const GETTING_ALLERGIES_FAILED = 'GETTING_ALLERGIES_FAILED'; 

//constant for resources
export const GETTING_RESOURCES = 'GETTING_RESOURCES';
export const GETTING_RESOURCES_SUCCESS = 'GETTING_RESOURCES_SUCCESS';
export const GETTING_RESOURCES_FAILED = 'GETTING_RESOURCES_FAILED';


//const for medication
export const GETTING_MEDS = 'GETTING_MEDS';
export const GETTING_MEDS_SUCCESS = 'GETTING_MEDS_SUCESSS';
export const GETTING_MEDS_FAILED = 'GETTING_MEDS_FAILED' 


//const for authorization
export const GETTING_TOKEN = 'GETTING_TOKEN';
export const GETTING_TOKEN_SUCESS = 'GETTING_TOKEN_SUCCESS';
export const GETTING_TOKEN_FAILED = 'GETTING_TOKEN_FAILED'; 


//const for user profile
export const GETTING_PROFILE = 'GETTING_PROFILE';
export const GETTING_PROFILE_SUCCESS = 'GETTING_PROFILE_SUCCESS';
export const GETTING_PROFILE_FAILURE = 'GETTING_PROFILE_FAILURE';


//const for user reports
export const GETING_REPORTS = 'GETING_REPORTS';
export const GETING_REPORTS_SUCCESS = 'GETING_REPORTS_SUCCESS';
export const GETING_REPORTS_FAILURE = 'GETING_REPORTS_FAILURE';


//const for patient timeline
export const GETTING_TIMELINE = 'GETTING_TIMELINE';
export const GETTING_TIMELINE_SUCCESS = 'GETTING_TIMELINE_SUCCESS';
export const GETTING_TIMELINE_FAILED = 'GETTING_TIMELINE_FAILED';


//const for paitent immune 
export const GETTING_IMMUNE = 'GETTING_IMMUNE';
export const GETTING_IMMUNE_SUCCESS = 'GETTING_IMMUNE_SUCCESS';
export const GETTING_IMMUNE_MORE_SUCCESS = 'GETTING_IMMUNE_MORE_SUCCESS';
export const GETTING_IMMUNE_FAILURE = 'GETTING_IMMUNE_FAILURE';


//const for messaging
export const GETTING_MESSAGE = 'GETTING_MESSAGE';
export const GETTING_MESSAGE_SUCCESS = 'GETTING_MESSAGE_SUCCESS';
export const GETTING_MESSAGE_MORE_SUCCESS = 'GETTING_MESSAGE_MORE_SUCCESS';
export const GETTING_MESSAGE_FAIL = 'GETTING_MESSAGE_FAIL';

//sent items
export const GETTING_SENT_MESSAGE = 'GETTING_SENT_MESSAGE';
export const GETTING_MESSAGE_SENT_SUCCESS = 'GETTING_MESSAGE_SENT_SUCCESS';
export const GETTING_MESSAGE_SENT_MORE_SUCCESS = 'GETTING_MESSAGE_SENT_MORE_SUCCESS';
export const GETTING_MESSAGE_SENT_FAIL = 'GETTING_MESSAGE_SENT_FAIL';


//const for booking appointment
export const BOOK_APP = 'BOOK_APP';
export const BOOK_APP_SUCCESS = 'BOOK_APP_SUCCESS';
export const BOOK_APP_FAIL = 'BOOK_APP_FAIL';
export const BOOK_APP_CLEANUP = 'BOOK_APP_CLEANUP';

//after booking, adding appointent
export const ADDING_APPOINT = 'ADDING_APPOINT';
export const ADDING_APPOINT_SUCCESS = 'ADDING_APPOINT_SUCCESS';
export const ADDING_APPOINT_FAIL = 'ADDING_APPOINT_FAIL';
export const ADDING_APPOINT_CLEANUP = 'ADDING_APPOINT_CLEANUP';


//get list of messaging receipted
export const GETTING_RECP = 'GETTING_RECP';
export const GETTING_RECP_SUCCESS = 'GETTING_RECP_SUCCESS';
export const GETTING_RECP_FAIL = 'GETTING_RECP_FAIL';



//appointment constants

//future appointments
export const GETTING_APPOINTMENT = 'GETTING_APPOINTMENT';
export const GETTING_APPOINTMENT_SUCCESS = 'GETTING_APPOINTMENT_SUCCESS';
export const GETTING_APPOINTMENT_FAILURE = 'GETTING_APPOINTMENT_FAILURE';

//completed appointments
export const GETTING_COMPLETED_APPOINTMENT = 'GETTING_COMPLETED_APPOINTMENT';
export const GETTING_COMPLETED_APPOINTMENT_SUCCESS = 'GETTING_COMPLETED_APPOINTMENT_SUCCESS';
export const GETTING_COMPLETED_APPOINTMENTT_FAILURE = 'GETTING_COMPLETED_APPOINTMENTT_FAILURE';


//Missed appointments
export const GETTING_MISSED_APPOINTMENT = 'GETTING_MISSED_APPOINTMENT';
export const GETTING_MISSED_APPOINTMENT_SUCCESS = 'GETTING_MISSED_APPOINTMENT_SUCCESS';
export const GETTING_MISSED_APPOINTMENTT_FAILURE = 'GETTING_MISSED_APPOINTMENTT_FAILURE';

//cancelled appointments
export const GETTING_CANCEL_APPOINTMENT = 'GETTING_CANCEL_APPOINTMENT';
export const GETTING_CANCEL_APPOINTMENT_SUCCESS = 'GETTING_CANCEL_APPOINTMENT_SUCCESS';
export const GETTING_CANCEL_APPOINTMENTT_FAILURE = 'GETTING_CANCEL_APPOINTMENTT_FAILURE';




//ACCOUNTS

//pending
export const GET_PENDING_INVOICES = 'GET_PENDING_INVOICES';
export const GET_PENDING_INVOICES_SUCCESS = 'GET_PENDING_INVOICES_SUCCESS';
export const GET_PENDING_INVOICES_MORE_SUCCESS = 'GET_PENDING_INVOICES_MORE_SUCCESS';
export const GET_PENDING_INVOICES_FAIL = 'GET_PENDING_INVOICES_FAIL';

//all
export const GET_ALL_INVOICES = 'GET_ALL_INVOICES';
export const GET_ALL_INVOICES_SUCCESS = 'GET_ALL_INVOICES_SUCCESS';
export const GET_ALL_INVOICES_FAIL = 'GET_ALL_INVOICES_FAIL';




//cancel appointment
export const START_APPOINTMENT_CANCELLATION = 'START_APPOINTMENT_CANCELLATION';
export const START_APPOINTMENT_CANCELLATION_SUCESSS = 'START_APPOINTMENT_CANCELLATION_SUCESSS';
export const START_APPOINTMENT_CANCELLATION_FAIL = 'START_APPOINTMENT_CANCELLATION_FAIL';